name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  black:
    runs-on: ubuntu-20.04
    container: ghcr.io/acceptablesoftware/python-testing-environment
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run black
        run: black --check src/osman

  isort:
    runs-on: ubuntu-20.04
    container: ghcr.io/acceptablesoftware/python-testing-environment
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run isort
        run: isort --check src/osman

  flake8:
    runs-on: ubuntu-20.04
    container: ghcr.io/acceptablesoftware/python-testing-environment
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run flake8
        run: flake8 src/osman

  mypy:
    runs-on: ubuntu-20.04
    container: ghcr.io/acceptablesoftware/python-testing-environment
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run mypy
        run: mypy src/osman
